# Page settings

baseURL = "https://guillermo.guerreroibarra.com"
languageCode = "en"
title = "Guillermo Guerrero Ibarra"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-57386726-5"

[params]
    author = "Guillermo Guerrero Ibarra"
    description = "Resume - Guillermo Guerrero Ibarra"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Guillermo Guerrero Ibarra"
        tagline = "Software Engineer"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Spain, Tarragona"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:guillermo@guerreroibarra.com"
        text = "guillermo@guerreroibarra.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/React"
        [[params.skills.list.items]]
        details = "Python/Ruby/Go"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "MongoDB/Redis/ElasticSearch"
        [[params.skills.list.items]]
        details = "DevOps/Docker/Kubernetes/Ansible"
        [[params.skills.list.items]]
        details = "Heroku/AWS/DigitalOcean"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Agile and Scrum"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "Universitat Rovira i Virgili"
        dates = "2009 - 2012"
        [[params.education.list]]
        degree = "Degree in Systems Engineering"
        university = "Universitat Rovira i Virgili"
        dates = "2003 - 2009"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Spanish"
        level = "Native"
        [[params.languages.list]]
        name = "Catalan"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Software"
        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "TV Shows"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "I am passionate about new technologies and everything that moves around software. I enjoy making efficient clean code and improving my skills as a programmer. In the last years I have been mainly working in web services also I enjoy with DevOps. Whenever I have some time off I enjoy with my personals projects, running, watching TV series and travelling to discover new places and cultures."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "June, 2021 - Present"
        company = "Deliveroo"
        details = ""
        [[params.experience.list.items]]
        details = "RoR, Scala and ReactJS"
        
        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "March, 2017 - June, 2021"
        company = "FCM Travel Solutions France"
        details = ""
        [[params.experience.list.items]]
        details = "RoR, Elixir (PoC, prototypes), Docker, Terraform, AWS, Ansible and Digital Ocean"

        [[params.experience.list]]
        title = "RoR backend developer (P/T Contractor)"
        dates = "March, 2019"
        company = "ADL Partner Hispania"
        details = ""
        [[params.experience.list.items]]
        details = "RoR and Heroku"

        [[params.experience.list]]
        title = "RoR backend developer (P/T Contractor)"
        dates = "March, 2017 – August 2017"
        company = "Charplanet (Nisgo)"
        details = ""
        [[params.experience.list.items]]
        details = "RoR, ReactJS, MongoDB and AWS"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "March, 2016 - March, 2017"
        company = "AirRefund"
        details=""
        [[params.experience.list.items]]
        details = "RoR, ReactJS, Heroku and AWS"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "April, 2015 – March, 2016"
        company = "Freelance"
        details=""
        [[params.experience.list.items]]
        details = "RoR, ReactJS, Angular, ElasticSearch, Vagrant, Chef, Ansible and Docker"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "August, 2013 – April, 2015"
        company = "Simpple"
        details=""
        [[params.experience.list.items]]
        details = "RoR, Vagrant and Chef"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "October, 2011 – July, 2013"
        company = "AST Research Group (URV)"
        details=""
        [[params.experience.list.items]]
        details="Java, Python, Ruby"

        [[params.experience.list]]
        title = "Software Developer and Sys Admin"
        dates = "December, 2009 – October, 2011"
        company = "Viajes para ti"
        details=""
        [[params.experience.list.items]]
        details="PHP"

        [[params.experience.list]]
        title = "Software Developer and Sys Admin"
        dates = "February, 2008 – September, 2009"
        company = "Emdep"
        details=""
        [[params.experience.list.items]]
        details="Visual Basic and .net c#"

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ryanfox1985"
        title = "ryanfox1985"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/guillermoguerreroibarra"
        title = "@guillermogue"
