# Page settings

baseURL = "https://guillermo.guerreroibarra.com/"
languageCode = "en"
title = "Guillermo Guerrero Ibarra"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-57386726-5"

[params]
    author = "Guillermo Guerrero Ibarra"
    description = "Resume - Guillermo Guerrero Ibarra"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Guillermo Guerrero Ibarra"
        tagline = "Software Engineer"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Spain, Tarragona"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:guillermo@guerreroibarra.com"
        text = "guillermo@guerreroibarra.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Ruby/Python/Go"
        [[params.skills.list.items]]
        details = "JavaScript/ReactJS/react-native"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "MongoDB/Redis/ElasticSearch"
        [[params.skills.list.items]]
        details = "DevOps/Docker/Kubernetes/Ansible"
        [[params.skills.list.items]]
        details = "Heroku/AWS/DigitalOcean"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Agile and Scrum"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "Universitat Rovira i Virgili"
        dates = "2009 - 2012"
        [[params.education.list]]
        degree = "Degree in Systems Engineering"
        university = "Universitat Rovira i Virgili"
        dates = "2003 - 2009"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Spanish"
        level = "Native"
        [[params.languages.list]]
        name = "Catalan"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Software"
        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "TV Shows"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "I am passionate about new technologies and everything that moves around software. I enjoy making efficient, clean code and improving my skills as a programmer. In the last years I have been mainly working in web services also I enjoy with DevOps. Whenever I have some time off I enjoy with my personals projects, running, watching TV shows and travelling to discover new places and cultures."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Developer"
        dates = "June 2021 - Present"
        company = "Deliveroo"
        details = "Deliveroo is a British online food delivery company and operates in several countries. I joined financial integrity team."
        [[params.experience.list.items]]
        details = "RoR, Scala and ReactJS"
        
        [[params.experience.list]]
        title = "Lead Developer"
        dates = "March 2017 - June 2021"
        company = "FCM Travel Solutions, France"
        details = "FCM Travel Solutions is the corporate travel business of the Flight Centre Travel Group. Provide different software solutions for companies and their employees like customized company dashboards, booking tools, approving system, etc. I joined to the development team (French division) and after a while I was promoted to lead developer with new responsibilities like taking decisions, design new software and assist newcomers."
        [[params.experience.list.items]]
        details = "RoR, Elixir (PoC, prototypes), Docker, Terraform, AWS, Ansible and Digital Ocean"

        [[params.experience.list]]
        title = "RoR backend developer (P/T Contractor)"
        dates = "March 2019"
        company = "ADL Partner Hispania"
        details = "ADL Partner Hispania is a Spanish company offering a fidelity and ERP software. I developed new features for this software, new endpoints and functionality to the API."
        [[params.experience.list.items]]
        details = "RoR and Heroku"

        [[params.experience.list]]
        title = "RoR developer (P/T Contractor)"
        dates = "March 2017 – August 2017"
        company = "Charplanet (Nisgo)"
        details = "Charplanet is an Asiatic startup and offers an advertisement screen service to companies. This service allows to companies to decide which advertisement render in their screens, these campaigns can be configured using some variables like time, localization, people around, etc. I developed new features and introduced ReactJS to this service."
        [[params.experience.list.items]]
        details = "RoR, ReactJS, MongoDB and AWS"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "March 2016 - March 2017"
        company = "AirRefund"
        details="AirRefund is a startup from FCM Travel Solutions group offering a claim service for flight disruptions using the EU flight compensation regulation. The startup has two websites, one for the clients to push their claims and another internal for the agents to be able to process these claims. I developed new features to improve the client's experience and also the agent's productivity."
        [[params.experience.list.items]]
        details = "RoR, ReactJS, Heroku and AWS"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "April 2015 – March 2016"
        company = "Freelance"
        details="I worked as a freelancer for some software consultancies, during these time I learned about Ruby on Rails, Django, react-native and DevOps."
        [[params.experience.list.items]]
        details = "RoR, ReactJS, react-native, Angular, ElasticSearch, Vagrant, Chef, Ansible and Docker"

        [[params.experience.list]]
        title = "RoR Developer"
        dates = "August 2013 – April 2015"
        company = "Simpple"
        details="Simpple is a Spanish software consultancy and offers software developed using Ruby on Rails to different clients."
        [[params.experience.list.items]]
        details = "RoR, Vagrant and Chef"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "October 2011 – July 2013"
        company = "AST Research Group (Cloudlab)"
        details="AST Research Group belongs to Universitat Rovira i Virgili, this group is focused on create software for distributed systems. I joined in the context of Real Cloud Project to offer a storage service multi-platform solution using OpenStack Swift for small companies like Dropbox. During my journey at the group, I did my final bachelor project."
        [[params.experience.list.items]]
        details="Java, Python and Ruby"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "December 2009 – October 2011"
        company = "Viajes para ti"
        details="Viajes para ti is a Spanish travel agency, the agency offers two distinguish experiences to travelers depending on the season, the agency during the winter offers Sky and Snowboard experiences and during the summer offers adventure packages. The agency has two main websites: [esquiades.com](https://esquiades.com) and [buscounchollo.com](https://buscounchollo.com). When I joined the development team, I developed small features to the old platform and in parallel I had the opportunity to rebuild the website from scratch."
        [[params.experience.list.items]]
        details="PHP"

        [[params.experience.list]]
        title = "Software Developer (P/T)"
        dates = "February 2011 – April 2011"
        company = "Universitat Rovira i Virgili"
        details="URV has different departments, I worked for statistical department to develop statistical functions in PHP to integrate later with Moodle at Statistical course. The professors use this functions in classroom and to correct the statistical exams."
        [[params.experience.list.items]]
        details="PHP"

        [[params.experience.list]]
        title = "Software Developer (P/T)"
        dates = "March 2010 – May 2010"
        company = "Universitat Rovira i Virgili"
        details="URV in collaboration with ASPACE built a web service to be able to create different questionnaires."
        [[params.experience.list.items]]
        details="PHP"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "February 2008 – September 2009"
        company = "Emdep"
        details="Emdep is a key player in the automotive industry, the company develops software to test control equipment for electric components in vehicles. Also does physical equipment’s to test fuse boxes, harness connectivity, etc. I joined the computer vision team, I mounted and prepared vision equipments and I had the opportunity to set up these equipments to customer sites."
        [[params.experience.list.items]]
        details="Visual Basic and .NET C#"

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ryanfox1985"
        title = "ryanfox1985"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/guillermoguerreroibarra"
        title = "@guillermogue"
        [[params.social.list]]
        icon = "fab fa-strava"
        url = "https://www.strava.com/athletes/31721949"
        title = "@guillermo"

    [params.footer]
        copyright = "Guillermo Guerrero Ibarra"